apiVersion: apps/v1
kind: Deployment
metadata:
  name: type-7-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: type-7-d
  template:
    metadata:
      labels:
        app: type-7-d
    spec:
      containers:
        - name: type-7-d
          image: docker.io/timattt/type-7-d:latest
          imagePullPolicy: Always
          env:
            - name: TYPE7_ACTIVE_PROFILE
              value: release
            - name: TYPE6_DATABASE_USER
              value: default-user
            - name: TYPE6_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_database_jdbc_url
            - name: TYPE6_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_database_port
            - name: TYPE6_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_database_password